title: "Jayden Raband"
author: "Jayden Rasband"
description: "Blog by Jayden Rasband"
theme: minima

# minima:
#   skin: classic
#   custom_css:
#     - /assets/css/custom.css


# Default Permalink
permalink: /:title/

# Base URL
url: "https://username.github.io"
baseurl: "/jaydenrasband"

# Header Navigation
header_pages:
  - index.md
  - about.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme
